driver:
  name: dokken
  privileged: true # because Docker, systemd, and sysctl
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

platforms:
- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd
    # This is needed because dcos-spartan.service does "modprobe dummy"
    volumes:
    - /lib/modules:/lib/modules:ro

suites:
  - name: default
    run_list:
      - recipe[dcos::default]
    attributes:
      dcos:
        config:
          master_list: ['127.0.0.1']
        docker_storage_driver: 'vfs'
