---
driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.5

suites:
  - name: default
    run_list:
      - recipe[dcos::default]
    attributes:
      dcos:
        config:
          master_list: ['127.0.0.1']
        ip-detect: lo
