#!/bin/sh
# Example ip-detect script using an external authority
# Uses the GCE metadata server to get the node's public
# ipv4 address
set -o nounset -o errexit

curl -fsSl -H "Metadata-Flavor: Google" \
http://169.254.169.254/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip
